# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ticket_service_pb2 as ticket__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ticket_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllFlights = channel.unary_unary(
                '/TicketService/GetAllFlights',
                request_serializer=ticket__service__pb2.TSAllFlightsRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.TSAllFlightsReply.FromString,
                _registered_method=True)
        self.GetFlightsByRoute = channel.unary_unary(
                '/TicketService/GetFlightsByRoute',
                request_serializer=ticket__service__pb2.FlightsByRouteRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.FlightsByRouteReply.FromString,
                _registered_method=True)
        self.BuyFlightPackage = channel.unary_unary(
                '/TicketService/BuyFlightPackage',
                request_serializer=ticket__service__pb2.BuyFlightPackageRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.BuyFlightPackageReply.FromString,
                _registered_method=True)
        self.Vote = channel.unary_unary(
                '/TicketService/Vote',
                request_serializer=ticket__service__pb2.VoteRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.VoteReply.FromString,
                _registered_method=True)
        self.PreCommit = channel.unary_unary(
                '/TicketService/PreCommit',
                request_serializer=ticket__service__pb2.PreCommitRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.PreCommitReply.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/TicketService/Commit',
                request_serializer=ticket__service__pb2.CommitRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.CommitReply.FromString,
                _registered_method=True)
        self.AbortVoting = channel.unary_unary(
                '/TicketService/AbortVoting',
                request_serializer=ticket__service__pb2.AbortVotingRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.AbortVotingReply.FromString,
                _registered_method=True)
        self.AbortTransaction = channel.unary_unary(
                '/TicketService/AbortTransaction',
                request_serializer=ticket__service__pb2.AbortTransactionRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.AbortTransactionReply.FromString,
                _registered_method=True)


class TicketServiceServicer(object):
    """The greeting service definition.
    """

    def GetAllFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlightsByRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyFlightPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortVoting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllFlights,
                    request_deserializer=ticket__service__pb2.TSAllFlightsRequest.FromString,
                    response_serializer=ticket__service__pb2.TSAllFlightsReply.SerializeToString,
            ),
            'GetFlightsByRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlightsByRoute,
                    request_deserializer=ticket__service__pb2.FlightsByRouteRequest.FromString,
                    response_serializer=ticket__service__pb2.FlightsByRouteReply.SerializeToString,
            ),
            'BuyFlightPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyFlightPackage,
                    request_deserializer=ticket__service__pb2.BuyFlightPackageRequest.FromString,
                    response_serializer=ticket__service__pb2.BuyFlightPackageReply.SerializeToString,
            ),
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=ticket__service__pb2.VoteRequest.FromString,
                    response_serializer=ticket__service__pb2.VoteReply.SerializeToString,
            ),
            'PreCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.PreCommit,
                    request_deserializer=ticket__service__pb2.PreCommitRequest.FromString,
                    response_serializer=ticket__service__pb2.PreCommitReply.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=ticket__service__pb2.CommitRequest.FromString,
                    response_serializer=ticket__service__pb2.CommitReply.SerializeToString,
            ),
            'AbortVoting': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortVoting,
                    request_deserializer=ticket__service__pb2.AbortVotingRequest.FromString,
                    response_serializer=ticket__service__pb2.AbortVotingReply.SerializeToString,
            ),
            'AbortTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTransaction,
                    request_deserializer=ticket__service__pb2.AbortTransactionRequest.FromString,
                    response_serializer=ticket__service__pb2.AbortTransactionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TicketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TicketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketService(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetAllFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/GetAllFlights',
            ticket__service__pb2.TSAllFlightsRequest.SerializeToString,
            ticket__service__pb2.TSAllFlightsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlightsByRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/GetFlightsByRoute',
            ticket__service__pb2.FlightsByRouteRequest.SerializeToString,
            ticket__service__pb2.FlightsByRouteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyFlightPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/BuyFlightPackage',
            ticket__service__pb2.BuyFlightPackageRequest.SerializeToString,
            ticket__service__pb2.BuyFlightPackageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/Vote',
            ticket__service__pb2.VoteRequest.SerializeToString,
            ticket__service__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/PreCommit',
            ticket__service__pb2.PreCommitRequest.SerializeToString,
            ticket__service__pb2.PreCommitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/Commit',
            ticket__service__pb2.CommitRequest.SerializeToString,
            ticket__service__pb2.CommitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortVoting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/AbortVoting',
            ticket__service__pb2.AbortVotingRequest.SerializeToString,
            ticket__service__pb2.AbortVotingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/AbortTransaction',
            ticket__service__pb2.AbortTransactionRequest.SerializeToString,
            ticket__service__pb2.AbortTransactionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
